# encoding: utf-8
---
recipe:
  Rx: patch
  description: >-
    Rime customizations

download_files: >-
  - https://raw.githubusercontent.com/Chernfalin/better-rime-dict/1eccb1b99f5c2936ac2e22162f23bab4419343b5/luna_pinyin.computer.dict.yaml
  - https://raw.githubusercontent.com/Chernfalin/better-rime-dict/1eccb1b99f5c2936ac2e22162f23bab4419343b5/luna_pinyin.place.dict.yaml
  - https://raw.githubusercontent.com/Chernfalin/better-rime-dict/1eccb1b99f5c2936ac2e22162f23bab4419343b5/luna_pinyin.poetry.dict.yaml

install_files: >-
  - *_patch.yaml
  - *.dict.yaml
  - rime.lua

patch_files:
  double_pinyin_flypy.custom.yaml:
    - patch/+:
        __include: rime_patch:/double_pinyin_flypy
  default.custom.yaml:
    - patch/+:
        __include: rime_patch:/default
  squirrel.custom.yaml:
    - patch/+:
        __include: squirrel_patch:/
